### ISSUE TITLE
weird exception

### ISSUE THREAD

**Issue by lexek** [lexek/chat#180]
```
2016.01.09 00:04:33 [MESSAGE_REACTOR_0] WARN  l.w.util.LoggingExceptionHandler - Exception processing: 7282 lexek.wschat.chat.DefaultMessageReactor$InboundMessageEvent@2851e0ce
java.lang.NullPointerException: null
	at lexek.wschat.services.UserService.cache(UserService.java:71) ~[wschat.jar:na]
	at lexek.wschat.services.ChatterService.getChatter(ChatterService.java:23) ~[wschat.jar:na]
	at lexek.wschat.chat.Room.getChatter(Room.java:79) ~[wschat.jar:na]
	at lexek.wschat.chat.handlers.AbstractModerationHandler.handle(AbstractModerationHandler.java:41) ~[wschat.jar:na]
	at lexek.wschat.chat.processing.HandlerInvoker.doHandle(HandlerInvoker.java:145) ~[wschat.jar:na]
	at lexek.wschat.chat.processing.HandlerInvoker.handle(HandlerInvoker.java:53) ~[wschat.jar:na]
	at lexek.wschat.chat.DefaultMessageReactor.process(DefaultMessageReactor.java:73) ~[wschat.jar:na]
	at lexek.wschat.chat.DefaultMessageReactor.onEvent(DefaultMessageReactor.java:106) ~[wschat.jar:na]
	at lexek.wschat.chat.DefaultMessageReactor.onEvent(DefaultMessageReactor.java:25) ~[wschat.jar:na]
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128) ~[wschat.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
```

**Comment by lexek** [comment]
closing this in favor of #232
