### ISSUE TITLE
Another exception in AuthenticationService

### ISSUE THREAD

**Issue by lexek** [lexek/chat#188]
```
Exception processing: 4000 lexek.wschat.security.AuthenticationService$AuthenticationEvent@4971b934
java.lang.IllegalStateException: null
	at lexek.wschat.chat.Connection.setUser(Connection.java:68) ~[wschat.jar:na]
	at lexek.wschat.security.AuthenticationService$AuthenticationServiceWorker.finishAuthentication(AuthenticationService.java:194) ~[wschat.jar:na]
	at lexek.wschat.security.AuthenticationService$AuthenticationServiceWorker.onEvent(AuthenticationService.java:186) ~[wschat.jar:na]
	at lexek.wschat.security.AuthenticationService$AuthenticationServiceWorker.onEvent(AuthenticationService.java:166) ~[wschat.jar:na]
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128) ~[wschat.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
```
todo: add toString to AuthenticationEvent (without key?)

**Comment by lexek** [comment]
Wasn't there a check for disconnected connections?
```
2016.02.09 13:40:13 [AUTHENTICATION_SERVICE_0] WARN  l.w.util.LoggingExceptionHandler - Exception processing: 298 AuthenticationEvent{connection=WebSocketConnectionAdapter{channel=io.netty.channel.ChannelMetadata@72ed5e58} Connection{protocol=lexek.wschat.frontend.ws.WebSocketProtocol@43f3fd3b, user=null, state=DISCONNECTED}, type=SID, name='null'}
java.lang.IllegalStateException: null
        at lexek.wschat.chat.Connection.setUser(Connection.java:68) ~[wschat.jar:na]
        at lexek.wschat.security.AuthenticationService$AuthenticationServiceWorker.finishAuthentication(AuthenticationService.java:203) ~[wschat.jar:na]
        at lexek.wschat.security.AuthenticationService$AuthenticationServiceWorker.onEvent(AuthenticationService.java:195) ~[wschat.jar:na]
        at lexek.wschat.security.AuthenticationService$AuthenticationServiceWorker.onEvent(AuthenticationService.java:175) ~[wschat.jar:na]
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128) ~[wschat.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_66]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
```

**Comment by lexek** [comment]
```
Exception processing: 193 AuthenticationEvent{connection=WebSocketConnectionAdapter{channel=io.netty.channel.ChannelMetadata@f8b8e9d} Connection{protocol=lexek.wschat.frontend.ws.WebSocketProtocol@1a77fbad, user=null, state=DISCONNECTED}, type=SID, name='null'}
java.lang.IllegalStateException: null
	at lexek.wschat.chat.Connection.setUser(Connection.java:68) ~[wschat.jar:na]
	at lexek.wschat.security.AuthenticationService$AuthenticationServiceWorker.finishAuthentication(AuthenticationService.java:201) ~[wschat.jar:na]
	at lexek.wschat.security.AuthenticationService$AuthenticationServiceWorker.onEvent(AuthenticationService.java:195) ~[wschat.jar:na]
	at lexek.wschat.security.AuthenticationService$AuthenticationServiceWorker.onEvent(AuthenticationService.java:175) ~[wschat.jar:na]
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128) ~[wschat.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
```

**Comment by lexek** [comment]
try making connection state volatile
