### ISSUE TITLE
Weird exception

### ISSUE THREAD

**Issue by lexek** [lexek/chat#224]
```
Exception processing: 7060 InboundMessageEvent{connection=WebSocketConnectionAdapter{channel=io.netty.channel.ChannelMetadata@5aaad938} Connection{protocol=lexek.wschat.frontend.ws.WebSocketProtocol@492d8d7d, user=User{wrappedObject=UserDto{id=6, name='noowai', role=ADMIN, color='#ff0000', banned=false, renameAvailable=false, email=null, emailVerified=false}, lastMessage=1459970327629}, state=AUTHENTICATED}, message={type=BAN, room=#main, name=cbip}}
java.lang.NullPointerException: null
	at lexek.wschat.services.UserService.cache(UserService.java:84) ~[wschat.jar:na]
	at lexek.wschat.services.ChatterService.getChatter(ChatterService.java:23) ~[wschat.jar:na]
	at lexek.wschat.chat.Room.getChatter(Room.java:79) ~[wschat.jar:na]
	at lexek.wschat.chat.handlers.AbstractModerationHandler.handle(AbstractModerationHandler.java:41) ~[wschat.jar:na]
	at lexek.wschat.chat.processing.HandlerInvoker.doHandle(HandlerInvoker.java:148) ~[wschat.jar:na]
	at lexek.wschat.chat.processing.HandlerInvoker.handle(HandlerInvoker.java:54) ~[wschat.jar:na]
	at lexek.wschat.chat.DefaultMessageReactor.process(DefaultMessageReactor.java:73) ~[wschat.jar:na]
	at lexek.wschat.chat.DefaultMessageReactor.onEvent(DefaultMessageReactor.java:106) ~[wschat.jar:na]
	at lexek.wschat.chat.DefaultMessageReactor.onEvent(DefaultMessageReactor.java:25) ~[wschat.jar:na]
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128) ~[wschat.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_77]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_77]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_77]
```

**Comment by lexek** [comment]
closing in favor of #232
